"""
README Generator - Generate README.md with Anki statistics display
"""
import json
from datetime import datetime
from pathlib import Path


class ReadmeGenerator:
    """Generate README.md with statistics and heatmap"""

    def __init__(self, data_dir="data", output_dir="output", repo_root="."):
        self.data_dir = Path(data_dir)
        self.output_dir = Path(output_dir)
        self.repo_root = Path(repo_root)

    def load_stats(self):
        """Load stats from JSON file"""
        stats_file = self.data_dir / "stats.json"
        if not stats_file.exists():
            raise FileNotFoundError(f"Stats file not found: {stats_file}")

        with open(stats_file, 'r', encoding='utf-8') as f:
            return json.load(f)

    def format_time(self, minutes):
        """Format minutes into readable time"""
        if minutes < 60:
            return f"{minutes}m"
        hours = minutes // 60
        mins = minutes % 60
        if mins == 0:
            return f"{hours}h"
        return f"{hours}h {mins}m"

    def generate_stats_table(self, stats):
        """Generate markdown stats table"""
        cards = stats['cards']

        table = """
| Metric | Value |
|--------|-------|
| Total Cards | {total:,} |
| Mature Cards | {mature:,} |
| Learning | {learning:,} |
| New Cards | {new:,} |
| Suspended | {suspended:,} |
| Current Streak | {streak} days |
| Weekly Reviews | {weekly_reviews:,} |
| Weekly Time | {weekly_time} |
""".format(
            total=cards['total'],
            mature=cards['mature'],
            learning=cards['learning'],
            new=cards['new'],
            suspended=cards['suspended'],
            streak=stats['streak'],
            weekly_reviews=stats['weekly_reviews'],
            weekly_time=self.format_time(stats['weekly_time_minutes'])
        )

        return table.strip()

    def generate_decks_table(self, stats, max_decks=10):
        """Generate table of top decks"""
        decks = stats.get('decks', {})

        # Sort by total cards
        sorted_decks = sorted(
            decks.values(),
            key=lambda d: d.get('total', 0),
            reverse=True
        )[:max_decks]

        if not sorted_decks:
            return ""

        lines = [
            "",
            "### Decks",
            "",
            "| Deck | Total | Mature | New |",
            "|------|-------|--------|-----|"
        ]

        for deck in sorted_decks:
            name = deck['name']
            if len(name) > 40:
                name = name[:37] + "..."
            lines.append(
                f"| {name} | {deck.get('total', 0):,} | "
                f"{deck.get('mature', 0):,} | {deck.get('new', 0):,} |"
            )

        return '\n'.join(lines)

    def generate_progress_bar(self, current, total, width=20):
        """Generate ASCII progress bar"""
        if total == 0:
            return "[" + " " * width + "] 0%"

        ratio = min(current / total, 1.0)
        filled = int(width * ratio)
        empty = width - filled

        percentage = int(ratio * 100)
        return f"[{'#' * filled}{'-' * empty}] {percentage}%"

    def generate_readme(self):
        """Generate full README.md content"""
        stats = self.load_stats()
        cards = stats['cards']

        # Calculate mastery percentage
        total_active = cards['total'] - cards['suspended']
        mastery_pct = (cards['mature'] / total_active * 100) if total_active > 0 else 0

        readme = f"""# Anki Statistics

> Auto-synced from Anki | Last updated: {stats['generated_at'][:10]}

## Review Activity

<picture>
  <source media="(prefers-color-scheme: dark)" srcset="output/heatmap-dark.svg">
  <source media="(prefers-color-scheme: light)" srcset="output/heatmap.svg">
  <img alt="Review Heatmap" src="output/heatmap.svg">
</picture>

## Statistics

{self.generate_stats_table(stats)}

## Progress

**Mastery Progress** ({cards['mature']:,} / {total_active:,} cards)

```
{self.generate_progress_bar(cards['mature'], total_active, 30)}
```

{self.generate_decks_table(stats)}

---

<sub>Generated by [anki-stats-sync](https://github.com/lori/anki-stats-sync)</sub>
"""

        return readme

    def write_readme(self, output_path=None):
        """Write README to file"""
        if output_path is None:
            output_path = self.repo_root / "README.md"
        else:
            output_path = Path(output_path)

        readme_content = self.generate_readme()

        with open(output_path, 'w', encoding='utf-8') as f:
            f.write(readme_content)

        return output_path


if __name__ == "__main__":
    generator = ReadmeGenerator()
    try:
        readme_path = generator.write_readme()
        print(f"Generated: {readme_path}")
    except FileNotFoundError as e:
        print(f"Error: {e}")
        print("Run data_exporter.py first to generate stats data")
